api:
  byCalendarYearMonth: https://api.aladhan.com/v1/calendar/:year/:month
  byCalendarByAdressURL: https://api.aladhan.com/v1/calendarByAddress
  byCityByDate: https://api.aladhan.com/v1/timingsByCity
  byDate: https://api.aladhan.com/v1/timings
  city: Nantes
  country: France
  forceDate: '2023-11-10'
  selectedMethod: 12
calculationMethods:
- description: Muslim World League
  id: 1
- description: Islamic Society of North America
  id: 2
- description: Umm Al-Qura University, Makkah
  id: 3
- description: Egyptian General Authority of Survey
  id: 4
- description: University of Islamic Sciences, Karachi
  id: 5
- description: Institute of Geophysics, University of Tehran
  id: 6
- description: Shia Ithna-Ashari, Leva Institute, Qum
  id: 7
- description: Gulf Region
  id: 8
- description: Kuwait
  id: 9
- description: Qatar
  id: 10
- description: Majlis Ugama Islam Singapura, Singapore
  id: 11
- description: Union Organization islamic de France
  id: 12
- description: "Diyanet \u0130\u015Fleri Ba\u015Fkanl\u0131\u011F\u0131, Turkey"
  id: 13
- description: Spiritual Administration of Muslims of Russia
  id: 14
- description: Moonsighting Committee
  id: 15
- description: Dubai, UAE
  id: 16
debug: false
device:
  volume: 25
enableScheduler: false
playlist:
  dirToServe: server/audio
  fileName: azan1.mp3
  port: 8000
